version: "3.8"
services:
  mc:
    image: itzg/minecraft-server
    container_name: spigot
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 3G
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ~/minecraft:/data
    restart: unless-stopped
